---

- name: VMWARE_GUEST | Ensure VMs exist in VMware
  vmware_guest:
    hostname: "{{ vmware_instance_vcenter_fqdn }}"
    username: "{{ vmware_instance_vcenter_username }}"
    password: "{{ vmware_instance_vcenter_password }}"
    name: "{{ vmware_instance_name }}"
    folder: "{{ vmware_instance_folder }}"
    datacenter: "{{ vmware_instance_datacenter }}"
    cluster: "{{ vmware_instance_cluster }}"
    state: poweredon
    validate_certs: false
    wait_for_ip_address: true
    template: "{{ vmware_instance_template }}"
    disk:
    - size_gb: "{{ vmware_instance_disk_size }}"
      type: thin
      datastore: "{{ vmware_instance_datastore }}"
    hardware:
      memory_mb: "{{ vmware_instance_memory }}"
      num_cpus: "{{ vmware_instance_cpus }}"
    networks:
    - name: "{{ vmware_instance_network }}"

- name: VMWARE_GUEST_FACTS | Get facts on the VM
  vmware_guest_facts:
    hostname: "{{ vmware_instance_vcenter_fqdn }}"
    username: "{{ vmware_instance_vcenter_username }}"
    password: "{{ vmware_instance_vcenter_password }}"
    name: "{{ vmware_instance_name }}"
    folder: "{{ vmware_instance_folder }}"
    datacenter: "{{ vmware_instance_datacenter }}"
    validate_certs: false
  register: vmware_instance_guest_facts

- set_fact:
    vmware_instance_host_ip: "{{ vmware_instance_guest_facts.instance.ipv4 }}"