---

- name: VMWARE_GUEST_INFO | Wait for VM to be assigned IP address
  local_action:
      module: vmware_guest_info
      hostname: "{{ vmware_instance_vcenter_fqdn }}"
      username: "{{ vmware_instance_vcenter_username }}"
      password: "{{ vmware_instance_vcenter_password }}"
      name: "{{ vmware_instance_name }}"
      folder: "{{ vmware_instance_folder }}"
      datacenter: "{{ vmware_instance_datacenter }}"
      validate_certs: false
  register: vmware_instance_guest_info
  retries: 24
  delay: 10
  until: vmware_instance_guest_info.instance.ipv4

- set_fact:
    vmware_instance_host_ip: "{{ vmware_instance_guest_info.instance.ipv4 }}"

- debug:
    var: vmware_instance_host_ip
