---

- name: check if instance exists
  include: "prepare.yml"

- name: including validation tasks for cloud-init
  include: "validate.yml"
  when: vmware_instance_cloudinit and not vmware_instance_exists

- name: including tasks for cloud-init
  include: "cloud_init.yml"
  when: vmware_instance_cloudinit and not vmware_instance_exists

- name: including tasks for standard templates
  include: "clone.yml"
  when: not vmware_instance_cloudinit and not vmware_instance_exists

- name: including tasks for existing instances
  include: "modify.yml"
  when: vmware_instance_exists

- name: Run setup commands on new guests
  include: "runcmd.yml"
  when: not vmware_instance_exists and vmware_instance_runcmd is defined and vmware_instance_runcmd != false

- name: Get the IP for the instance
  include: "get_ip.yml"
  when: vmware_instance_wait_for_ip
