---

- name: check if instance exists
  include: "prepare.yml"

- name: including validation tasks for cloud-init
  include: "validate.yml"
  when: vmware_instance_cloudinit and not vmware_instance_exists

- name: including tasks for cloud-init
  include: "cloud_init.yml"
  when: vmware_instance_cloudinit and not vmware_instance_exists

- name: including tasks for standard templats
  include: "clone.yml"
  when: not vmware_instance_cloudinit and not vmware_instance_exists

- name: including tasks existing instnaces
  include: "modify.yml"
  when: vmware_instance_exists
