---
- name: VMWARE_GUEST_FACTS | Wait for VMware tools to become available
  vmware_guest_tools_wait:
    hostname: "{{ vmware_instance_vcenter_fqdn }}"
    username: "{{ vmware_instance_vcenter_username}}"
    password: "{{ vmware_instance_vcenter_password }}"
    name: "{{ vmware_instance_name }}"
    folder: "{{ vmware_instance_folder }}"
    validate_certs: false

- name: VMWARE_VM_SHELL | Wait until shell is available
  vmware_vm_shell:
    hostname: "{{ vmware_instance_vcenter_fqdn }}"
    username: "{{ vmware_instance_vcenter_username}}"
    password: "{{ vmware_instance_vcenter_password }}"
    datacenter: "{{ vmware_instance_datacenter }}"
    vm_id: "{{ vmware_instance_name }}"
    validate_certs: false
    vm_username: root
    vm_password: "{{ vmware_instance_root_password }}"
    vm_shell: /usr/bin/printf
    vm_shell_args: " hello world"
  register: task_result
  retries: 50
  until: not task_result.failed
  ignore_errors: true

- fail:
    msg: 'Not able to log into instance and run command'
  when: task_result.failed

- name: PAUSE | Wait for VM to finish booting
  pause:
    seconds: 20

- name: Run commands on host
  vmware_vm_shell:
    hostname: "{{ vmware_instance_vcenter_fqdn }}"
    username: "{{ vmware_instance_vcenter_username}}"
    password: "{{ vmware_instance_vcenter_password }}"
    datacenter: "{{ vmware_instance_datacenter }}"
    vm_id: "{{ vmware_instance_name }}"
    validate_certs: false
    vm_username: root
    wait_for_process: true
    vm_password: "{{ vmware_instance_root_password }}"
    vm_shell: /usr/bin/printf
    vm_shell_args: ' ''hello world'';{% for item in vmware_instance_runcmd %}{{ item }};{% endfor %}'
